### ISSUE TITLE
关于此代理的内存优化——（第一次在github上发issue

### ISSUE THREAD

**Issue by arloor** [xtuhcy/socks5-netty#2]
## 致谢

感谢作者提供了一个很好的学习 netty socks5 的项目。

之前一直想写一个代理，以了解http原理，最终目的是达到大陆到国外的不可描述的目的。作者的项目是很好的sslocal-加密 的项目。

## 问题描述

拿到这个项目，看了很久之后感觉作者写的很完善，没什么好自己动手修改的地方。

然后就看作者的具体实现。用jdk9带的 java misson control 工具查看了一下项目的内存情况。发现当长时间运行，产生多个与远端的连接时，程序占用的内存非常大，而且使用jmc的full gc工具也无法进行垃圾回收。具体情况可以见附图。
![default](https://user-images.githubusercontent.com/21768987/38613714-5a0eba2a-3dbd-11e8-9f10-656183a46c4f.PNG)
![default](https://user-images.githubusercontent.com/21768987/38613715-5a6afede-3dbd-11e8-90ee-60d993050838.PNG)

看jmc中的线程信息时，发现：出现了350多个类nioEventLoopGroup-350-1的runnable的线程。

结合学习的netty知识判断和对您源码的阅读，判断是在`Socks5CommandRequestHandler.channelRead0()`方法中的`EventLoopGroup bossGroup=new NioEventLoopGroup();`语句导致的。这句话导致——每次需要代理新建到远程服务器的连接时，都创建了一个NioEventLoopGroup。而且经过上面fullGC的测试，这些NioEventLoopGroup还不能被回收。

## 问题解决

netty实战告诉我，服务器端有两个NioEventLoopGroup，客户端有一个NioEventLoopGroup。

所以我设想，只使用一个NioEventLoopGroup固定的处理所有对远程的channel。

我做出了如下修改
在`Socks5CommandRequestHandler`中增加：

```java
    private EventLoopGroup bossGroup;
    public Socks5CommandRequestHandler(ProxyServer proxyServer) {
        bossGroup=proxyServer.getBossGroup();
    }
```

即在ProxyServer中创建一个单独的NioEventLoopGroup，在Socks5CommandRequestHandler，导入这个NioEventLoopGroup,用以管理与远程的连接。

## 效果

在JMC的线程页面中显示只有3个NioEventLoopGroup（编号分别位2、3、4）。当执行full gc时，内存占用降低到13.8M。这个数据非常稳定，13.8M。
![default](https://user-images.githubusercontent.com/21768987/38613727-61df9c4c-3dbd-11e8-8dcf-e10bc88e0691.PNG)
![default](https://user-images.githubusercontent.com/21768987/38613728-623b1270-3dbd-11e8-8e35-08ef9e647e98.PNG)

## 谢谢

这是第一次在github上提交issue。也是第一次利用自己的知识解决java内存相关的问题。感觉很宝贵。

**Comment by xtuhcy** [comment]
多贡献代码~

**Comment by jingb** [comment]
@arloor  好像和http://normanmaurer.me/presentations/2014-http-netty/slides.html#46.0 说的是一个事  
HTTP Server that needs to pipe to external services which reduce context-switching to minimum
那一页
