### ISSUE TITLE
the proxy service is not installed -指定的服务未安装

### ISSUE THREAD

**Issue by petma** [xtuhcy/socks5-netty#6]
pxoxy.bat start
the proxy service is not installed -指定的服务未安装

**Comment by petma** [comment]
要先调用proxy install,再执行proxy start就行了

**Comment by xiaolisheng** [comment]
为什么发给我




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"petma"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 下午4:14
收件人:&nbsp;"xtuhcy/socks5-netty"<socks5-netty@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [xtuhcy/socks5-netty] the proxy service is not installed -指定的服务未安装 (#6)




要先调用proxy install,再执行proxy start就行了
